name: other_branches
on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches-ignore: [ "main" ]
permissions:
  contents: read
jobs:
  build-docker-image:
    # 실행 환경 지정
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: '3306'
          container port: '3306'
          character set server: 'utf8'
          mysql version: '8.0.41'
          mysql database: ${{ secrets.MYSQL_DATABASE }}
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'

      # 분리한 application.yml 생성
      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      # Build Spring Boot Applicaion
      - name: Set up Permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # Build Docker Image
      - name: BuiSetting CI - GitHub Actionld Docker Image
        run : docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simpleboard_action .

      # DockerHub Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Don't input your account password

      # DockerHub Image Push
      - name: Push Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simpleboard_action